### ISSUE TITLE
Diagram and Sidebar Reset / Deselect

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-plugins#10]
As a user I want to be able to reset the view quickly.

ACs:
- [ ] 1) ~~add a "clear all" button in the top right corner of the sidebar~~
- [ ] 2) ~~pressing "clear all" deselect all selected devices in the sidebar and also in the left overview / map~~
- [x] 3) clicking somewhere in the "empty area of the overview/map" deselects all selected devices in the sidebar and also in the left overview / map

**Comment by trusz** [comment]
We will implement 1) and 2) in the following ticket:
- https://github.com/sprinteins/oscd-plugins/issues/27
