### ISSUE TITLE
Hide/Display given column

### ISSUE THREAD

**Issue by michelguerin** [sprinteins/oscd-plugins#103]
# User Story: Hide/Display Column Feature with Eye Icon

**As** a User
**I want to** hide or display a given column using an eye icon
**So that I** can manage the visibility of columns and keep the interface clean and focused on the relevant information.

## Acceptance Criteria:

- [ ] Each column should have an eye icon next to its header.
- [ ] Clicking the eye icon should hide the column and compact it to the side with just the title visible.
- [ ] The compacted column should display the title vertically on the side.
- [ ] Clicking the eye icon again should display the column back to its original state.

**Comment by michelguerin** [comment]
@LissiEitel & @PhilipLeddin feel free to change the acceptance criteria according to updated vision of this feature.

**Comment by illia-solovei-s1** [comment]
> [@LissiEitel](https://github.com/LissiEitel) how should the column collapse ?
> 
> We have two options in mind :
> 
> * horizontal collapse, easy to be done and no jumping columns when using the feature, but also one win no free place.
> * vertical collapse, the layout changes dynamically and the user wins free place.

![Image](https://github.com/user-attachments/assets/7f37f434-a459-41b0-83fa-8e672db72d02)

**Comment by michelguerin** [comment]
@LissiEitel I saw your new designs ;)

![Image](https://github.com/user-attachments/assets/900313bd-6b2b-4d9b-b69f-39f31b477748)

**Comment by illia-solovei-s1** [comment]
Building first prototype according to the early design build above
