### ISSUE TITLE
Documents and Templates

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-plugins#108]
As a user, I want to see my documents and templates in the AutoDoc plugin so that I can always manage them there.

ACs:

- [ ] there is a tab: Documents that contains all documents
- [ ] Documents are displayed in a list containing: Name, type, description and version
- [ ] there is a tab: Templates that contains all templates
- [ ] Templates are displayed in a list that contains Name and Description

**Comment by LissiEitel** [comment]
@PhilipLeddin still needed? because with dont have a document overview, only a template overview. This was implemented in sprint 4 [#141](https://github.com/sprinteins/oscd-plugins/issues/141)

**Comment by PhilipLeddin** [comment]
@LissiEitel , you are right -> closed

**Comment by PhilipLeddin** [comment]
dont have a document overview, only a template overview. This was implemented in sprint 4 https://github.com/sprinteins/oscd-plugins/issues/141
