### ISSUE TITLE
Compile a basic document

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-plugins#110]
As a user, I want to be able to design and compile a document in order to create individual documents for documentation purposes.

ACs:
- [x] It is possible to compile a template from elements
- [x] there is a add button to add elements like: title, description text and image or logo
- [x] Classic elements can be: title, description text and image or logo

**Comment by PhilipLeddin** [comment]
![Image](https://github.com/user-attachments/assets/d100267b-9ae4-4bab-9ff9-66df25be7dbe)
