### ISSUE TITLE
[SPIKE] : XML File structure for type designer

### ISSUE THREAD

**Issue by michelguerin** [sprinteins/oscd-plugins#121]
# User Story: Spike for the XML structure of the type designer plugin

**As** a developer
**I want to** have a better comprehension of the XML data structure
**So that I** make CRUD operations based on these data

## Acceptance Criteria:

- [ ] Create a file structure inside DataTypeTemplates of an `scd` file.
- [ ] This structure should be in a named `Private` field.
- [ ] Create a dummy file to play around with.
