### ISSUE TITLE
Drag and Drop Elements to reorder Types

### ISSUE THREAD

**Issue by michelguerin** [sprinteins/oscd-plugins#140]
#Story: Drag and Drop Elements to reorder Types

**As a** User
**I want to** drag and drop types to rearrange them inside the same column
**So that I** can set a custom order independently from the creation

## Acceptance Criteria:

- [ ] Types should be draggable within their respective columns.
- [ ] Types should be droppable within their respective columns.
- [ ] A drop space should appear to give the user a clue where to leave the card.
- [ ] Dropping a type should be persistent in the XML file.

Hints:

    sync with Lissi (Multiselect)

**Comment by michelguerin** [comment]
Linked to #94

**Comment by illia-solovei-s1** [comment]
Taken into a spike dev trial

**Comment by illia-solovei-s1** [comment]
Spike is described here: #166

**Comment by michelguerin** [comment]
Closed because unnecessary.
