### ISSUE TITLE
Create a new template

### ISSUE THREAD

**Issue by salvar3nga** [sprinteins/oscd-plugins#143]
As a user, I want to be able to create a new template from scratch, so that I can easily generate templates for future use.

AC:

- [x] A clearly labeled "add template" button is visible on the template overview page
- [x] Clicking the button navigates to a new template creation form page
- [x] A template can be compiled by adding different elements such as heading, image etc...
- [x] Save button exists to allow users to save the template

![Image](https://github.com/user-attachments/assets/88f2e6c3-3d99-424d-b1eb-2154505ed8b6)

![Image](https://github.com/user-attachments/assets/5bef346b-002e-4774-8518-087f258e74c0)
