### ISSUE TITLE
Generate pdf document from template

### ISSUE THREAD

**Issue by salvar3nga** [sprinteins/oscd-plugins#144]
As a user, I want to be able to generate a PDF document from a selected template, so that I can easily download or share a formatted, printable version of the template content.

AC:

- [x] In the template overview table, each template has a download icon in the actions column
- [x] Clicking the icon triggers the generation of a PDF document based on the structure of the template
- [x] Once PDF is ready, the file should automatically download to the user's device
- [ ] Signal list will be displayed "similar" to a xls signal list

**Comment by PhilipLeddin** [comment]
<img width="1203" alt="Image" src="https://github.com/user-attachments/assets/526d55be-1901-42f6-98fe-cba1e4c971f3" />

**Comment by PhilipLeddin** [comment]
![Image](https://github.com/user-attachments/assets/1d5dd0a1-8e40-4f28-b64e-9e5c39fbd078)

**Comment by michelguerin** [comment]
Two options here: 
* using the print PDF function from the browser
* use a dedicated JS library
