### ISSUE TITLE
Create signal list custom element

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-plugins#154]
As a user I want to be able to add signal liste tables to the templates to allow displaying signal lists in my generated documentations.

- [x] possibility to add signal list tables to templates
- [x] there is a area in top to choose columns 
- [x] there is a second area in the bottom to choose message types
- [x] the top area has a text and regex filter option in the right
- [x] the bottom area has a text and regex filter option for IEDs in the right
- [x] possibilty to select or deselect columns
- [x] when selected > the text and regex filter in the same row is active
- [x] when deselected > the text and regex filter in the same row is inactive
- [x] signal list module will be stored to template file

**Comment by PhilipLeddin** [comment]
![Image](https://github.com/user-attachments/assets/a61bb089-930d-4a39-a6a2-485cca95c0bc)

**Comment by salvar3nga** [comment]
Columns should be organizable (change order)

Select all checkbox in the top left

Instead of "Column," display the respective "Type"
Additionally, show a number

Example:

Column 4 Alert Text:
Alert Text Example
Example: Column 5: "IED Name"
Right column: "QHWTA_7"

Instead of Regex > Substring Search
