### ISSUE TITLE
Duplicate Type

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-plugins#160]
As a user i want to delete types to be able to delete types I do not need any more.

ACs:

- [x] possibility to duplicate types by a menu at the element (see design)
- [x] duplicated elements will be displayed directly under the "source element"
- [ ] when duplicating types > type refs should be duplicated as well

![Image](https://github.com/user-attachments/assets/1644950a-c755-4685-999f-4fde27ebe5e5)
