### ISSUE TITLE
Expand/Collapse Ref-Elements on a click on an element type

### ISSUE THREAD

**Issue by illia-solovei-s1** [sprinteins/oscd-plugins#164]
### Story: Display/Collapse Ref-Elements on a click on an element type

As a User
I want to be able to expand or collapse a desired element type to show its hidden ref-elements.
So that I can see the ref-elements attached to that element.

AC:

- [x] Display a small indicator on the left that the element is either expanded or collapsed if the parent element contains any ref-elements.
- [x] Render all parent-elements collapsed by default, so that no ref-elements are shown.
- [x] It is expected that the sidebar drawer and the expansion of the ref-elements will be rendered simultaneously, so when a parent is clicked, both the drawer and the refs will be shown.
