### ISSUE TITLE
Setup Diagram

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-plugins#19]
As a user I want an overview over the whole network to be aware of all IEDs and connections between them.

ACs:
- [x] setup zoomable and movable diagram 
- [x] create diagramm design based on OpenSCD styling
- [x] create IED design based on OpenSCD styling
