### ISSUE TITLE
 IEDs and Connections

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-plugins#2]
As a user, I want to get an overview of the network including the IEDs and connections and gain insight.

ACs:
- [x] add IEDs to the network plan
- [ ] add the bus / network
- [x] add connections based on physical wires between the IEDs

**Comment by trusz** [comment]
we have not implemented "add the bus / network"
