### ISSUE TITLE
Four column design

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-plugins#206]
As a user, I want to organize my types and type references in a four-column design.

ACs:

- [ ] there are the columns Bay Types, Conductive Equipment Types, Function Types and Logical Node Types from left to right
- [ ] the columns can be shown and hidden as before
- [ ] the columns have corresponding headings

**Comment by PhilipLeddin** [comment]
![Image](https://github.com/user-attachments/assets/6e4c7fe2-34be-485f-9c2f-ad99d61266c1)
