### ISSUE TITLE
Add Equipments

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-plugins#218]
As a user, I want to be able to easily select the appropriate equipment from a list when creating equipment in order to create it in accordance with the standard.

ACs:
- [x] Dropdown shows the list of all equipments separated by scope (`General`and `Conducting`)
- [x] New types get an iterative name based on its naming, following this convention : `Circuit Breaker 1`for `Circuit Breaker`equipment and so on
- [x] Name displayed in the "type-box"

Hints:
- Name and description can be added later in the sidebar

-  [Conducting_Equipment.txt](https://github.com/user-attachments/files/17935657/Conducting_Equipment.txt)
- See Mural to et the mapping between equipments names and the types

**Comment by PhilipLeddin** [comment]
![Image](https://github.com/user-attachments/assets/c9b1cc6b-2138-4e03-afd7-ce1c903617df)

**Comment by PhilipLeddin** [comment]
I linke it, maybe "Choose type of conductive equipment"
and the popup similar to existing ones in OpenSCD

**Comment by LissiEitel** [comment]
If it is in a pop up like the existing ones, then i would prefer to specify also name and description in the pop up to be consistent. But then the sidebar would be obsolete.

**Comment by michelguerin** [comment]
After discussion with @LissiEitel, the retained version will be a dropdown displayed next to the add button.
In the dropdown, the list will be splitted in to `General Equipments` and `Conducting Equipments`

**Comment by michelguerin** [comment]
First thing to do : map equipments list with standard types

**Comment by PhilipLeddin** [comment]
TypeDesigner:

Make the "Add" button more prominent
Equipment:

Each type under General and Conductive Equipment should be counted separately
Example:

Valve 1
Filters 1
Valve 2
Filters 2
Valve 3
Circuit Breaker_1
Circuit Breaker_2
Same counter for functions 1 > 2 > 3…:

Function_custom 1
Function_custom 2
Equipment functions should not be moved out of the function in the bay. > Restriction
