### ISSUE TITLE
Select bay and all IEDs in it

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-plugins#22]
As a user I want to select all IEDs in the whole bay by by clicking on the area around the bay. 

ACs:
- [ ] it is possible to click on the bay-area and select all IEDs in it
- [ ] the bay and all IEDs in it will be highlited
- [ ] all IED details will be selected in the sidebar

Hints:
- Review Feedback
