### ISSUE TITLE
Connect DO to LC to LP

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-plugins#222]
As a user, I want to be able to assign data attributes from IEDs to logical nodes from other IEDs using LC that I can create. That functionality is based on following logic:

- [x] it is possible to connect one "Data Object" port to one "Logical Conditioner" port 
- [x] it is not not possible to connect "Data Objects" to "Logical Phyiskal Input/Output" and vice versa
- [x] it is possible to connect one "Logical Conditioner" port to one "Data Objects" port
- [x] it is possible to connect each "Logical Conditioner" port (could be several) to several "Logical Phyiskal Input/Output" ports (one port per LP)
~~- [ ] there can be only one connection for each "Logical Conditioner" port~~
~~- [ ] there can be several connections for each "Logical Physical Input/Output" port~~
(will be handled in #373)

Backend:

- [x] Writing the created assignments to the SCD file

**Comment by michelguerin** [comment]
@tamasrusz is this US treating this second part : 
<img width="495" alt="Image" src="https://github.com/user-attachments/assets/654fa89d-0ff9-4f57-9f41-78525c113ebd" />

**Comment by michelguerin** [comment]
Work to be done here is unclear for the team @PhilipLeddin

**Comment by LissiEitel** [comment]
> [@tamasrusz](https://github.com/tamasrusz) [@LissiEitel](https://github.com/LissiEitel) is this US treating this part from mural?

No this was only an idea from me how a minimized assignment could look. 


I think the ticket ist about making the connection lines between the three elements which the user has added in the canvas and making the assignment "done". But maybe we need a clarification again for that, because depending on the added elments not all connections are possible.

There were five different ways:

<img width="913" alt="Image" src="https://github.com/user-attachments/assets/215ffe06-6b34-45db-9595-01300984e73b" />

@tamasrusz @PhilipLeddin what do you say?

**Comment by PhilipLeddin** [comment]
Base logic was added in ticket description @michelguerin @LissiEitel @AbdelazizTina-dev (advanced logic is visible in screenshot)
