### ISSUE TITLE
Persist type creation to XML file

### ISSUE THREAD

**Issue by michelguerin** [sprinteins/oscd-plugins#226]
Story: Persist type creation to XML file

**As** a User
**I want to** persist type element to the xml file
**So that** I can use the scd file in my process.

## Acceptance Criteria:

- [x]  Bay Type element as child of <VoltageLevel name="Template">
- [x] Equipments as child of  <VoltageLevel name="Template">
- [x] Functions as child of <FunctionTemplate>

**Comment by michelguerin** [comment]
First thing to do as ACs : map columns to XML structure

**Comment by michelguerin** [comment]
Remove the select input on the function column as it is not align with the IEC61850-90-30 revision.
Fixing Drag'n'drop as per new requirements.
