### ISSUE TITLE
DO bar

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-plugins#228]
As a user i want to see my selected IED and the data structure of it, to find and select fast the correct data object for the mapping.

ACs:

- [x] Dropdown for selection of IED
- [x] Tree view from data structure of selected IED. Starting with LDs, then LNs, then DOs.
- [x] Searchbar to find needed DO faster in tree view. (Possible to search for text in IED, LD, DO)
- [x] The result will be opened in the hierarchy and only results will be displayed in DO-Bar
- [x] It should be possible to select multiple DO in the IED-Tree-View
- [x] The selected DOs should be highlited and have a checkbox icon in DO-Bar

Wireframe:

<img width="140" alt="Image" src="https://github.com/user-attachments/assets/b9d96fab-3f76-48cb-a18e-6d537f0eb966" />

**Comment by michelguerin** [comment]
@AbdelazizTina-dev is working on a spike, creating a svelte component based on our core shadcn svelte library.

**Comment by michelguerin** [comment]
@AbdelazizTina-dev ongoing work review done.

**Comment by michelguerin** [comment]
Issue was seen testing the component in integrated mode : using the shadcn element is not working with shadow dom.

**Comment by michelguerin** [comment]
This AC `When selecting a DO from the IED-Tree-View it will be displayed in the diagram` should be moved to the issue concerning the diagram

**Comment by michelguerin** [comment]
The query is now getting the LDevices and DOIs but should get the DOs from the DataTypeTemplates > LNodeTypes elemenets.

**Comment by PhilipLeddin** [comment]
Specific filtering for DOs similar to Bearingpoint solution 

Ingnore <LN0> and all content 

Ignore all data in <Communication> and <Access Point> 

Only search for LNs in IEDs

**Comment by PhilipLeddin** [comment]
![Image](https://github.com/user-attachments/assets/5cab5b83-333b-4847-895a-f59d32918127)
