### ISSUE TITLE
LP Bar

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-plugins#229]
As a user i want to see my LPs, to know which LPs i have to mapp. 

- [x] List of LPs
- [x] Sorted into LPDI and LPDO
- [x] Search bar to find LP
- [x] Button to add a new LP
- [x] The selected LP will be displayed in column "Logical Physical Input/Output"
- [x] The selected LP in the sidebar (LP-Bar) will be highlited and will have a checkbox icon

Later:
- Quick Filter for unlinked, linked, input and output

Wireframe:
<img width="226" alt="Image" src="https://github.com/user-attachments/assets/00fe2018-8484-4afb-a770-70a81c89cb21" />

**Comment by michelguerin** [comment]
@PhilipLeddin @tamasrusz :
We might need an XML scd file example to understand the whole structure (are LPDIs and LPDOs part of a written element in the XML file ?)

**Comment by PhilipLeddin** [comment]
Where will the LPs be: 
- files in a folder (local) / DB (compas)? 
OR
- LPs in the SCD itself?

**Comment by PhilipLeddin** [comment]
Example file:

https://sprinteins-my.sharepoint.com/shared?listurl=https%3A%2F%2Fsprinteins%2Esharepoint%2Ecom%2Fsites%2FTransnetBW%2FFreigegebene%20Dokumente&id=%2Fsites%2FTransnetBW%2FFreigegebene%20Dokumente%2FSCDs%2FLPs%2FI%5FO%5FCenter%2Dtest%2D2%2Escd&parent=%2Fsites%2FTransnetBW%2FFreigegebene%20Dokumente%2FSCDs%2FLPs

**Comment by michelguerin** [comment]
This US scope and attached PR contains the logic without links to the XML file (using static data)

**Comment by michelguerin** [comment]
Review has been done

**Comment by PhilipLeddin** [comment]
Change: 
- When adding further LPs they should be name automatically LP 1, LP 2, LP 3, LP ...
- Change "LP Instance" to "LP Number".

**Comment by PhilipLeddin** [comment]
When Editing a LP: Only allow editing name and description

**Comment by PhilipLeddin** [comment]
When deleting a LP 1, the other LPs will be renamed based on that. So LP 2 will become LP 1.
