### ISSUE TITLE
Diagram Canvas

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-plugins#230]
As a user a need a canvas area to mapp there my DOs with my different LP Types with a LC.

- [x] Canvas area that displays "Data Objects", "Logical Conditioner", "Logical Physical Input/Output" in three columns
- [x] DOs will be displayed in DO column
- [x] LCs will be displayed in LC column
- [x] LPs will be displayed in LP column
- [x] It is possible to connect those elements
- [x] When selecting a DO from the IED-Tree-View it will be displayed in the diagram

~~[ ] There is a button in the LC column to add LCs~~ Issue #291 

Wireframe:

<img width="449" alt="Image" src="https://github.com/user-attachments/assets/4cf00dab-9c96-4371-8581-533338f3a53e" />

**Comment by PhilipLeddin** [comment]
Possible Diagrams:
<img width="1387" alt="Image" src="https://github.com/user-attachments/assets/cdfd2098-3d42-447e-9184-c3cbe8182a5e" />

**Comment by Xenon27** [comment]
A REPL to connect nodes with an SVG instead of svelte flow.

https://svelte.dev/playground/2095795b823e400faaf39246ae861ce2?version=5.17.2

**Comment by Xenon27** [comment]
#267 I can display Nodes and connect them. Missing actual data from the xml file and persisting that information.
