### ISSUE TITLE
Cable Name UU-ID Check (Sidebar)

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-plugins#36]
The new created cable UU-ID should be unique to avoid redundant names for cables. 

ACs:
- [ ] unique UU-ID
- [ ] automatically check wether there is already an existing cable name with the entered name
- [ ] only check new cable names created in the Network Explorer (older cable names should not be checked)
- [ ] show a error dialog if there is already a same-named cable name
