### ISSUE TITLE
Spike: Parent and Child elements 

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-plugins#62]
Es soll möglich sein Type-Elemente als Parent-Types anzulegen und mehrere Children-Types davon anzulegen.

ACs:
Aufbau
- [ ] Ein Parent-Child soll "N" Children-Types haben können
- [ ] Ein Children Type soll weitere "N" Children haben können
- [ ] Werden für ein Children weitere Sub-Children definiert kann entschieden werden die Zuweisung zum Parent aufzuheben oder bestehen zu lassen
- [ ] Alle folgenden Elemente sollen als Parent und auch Child verwendbar sein: Substation, Voltage Levels, Bays, IEDs und LNs

Änderungen
- [ ] Wird der Parent-Type geändert werden alle Children-Types und deren Children-Types angepasst
- [ ] Es soll möglich sein Änderungen an den Children-Types vorzunehmen, allerdings werden bei einem Update des Parent-Types automatisch diese Änderungen überschrieben

Hinweise:
- Elemente = Substation, Voltage Levels, Bays, IEDs und LNs

Beispiel:
Parent IED B.scd
>> Child IED B 1.scd
>>>> Child IED B 3.scd 
>> Child IED B 2.scd

**Comment by michelguerin** [comment]
Nicely transcribed. To continue our discussions from yesterday : 
* On the UX perspective, I'm wondering if the children characteristics coming from the parent should not be **unchangeable** (like viral license in open source), i.e. :
  * a parent has a given characteristic (changeable or not, that has no effect), and is selected to go along with the child. 
  * that characteristic is marked has unchangeable on the child, to have a consistent behavior through the modifications chains and to avoid side effects.

* When creating a full bay type with all inner components, does it make sense to create those inner components as stand alone types as if they were imported inside the bay type? (@PhilipLeddin, you mentioned the atomic components of figma for example, and I can picture this here as well)
  * Does it have a real meaning on the UI side ? I don't know how complex the design will be. Do we need this kind of library style features ? Will this make the process of cloning or parenting the types easier ?

**Comment by LissiEitel** [comment]
"Ein Parent-Child soll "N" Children-Types haben können"

I thought if a TYPE is used in a project than its a childern of the PARENT Type but the CHILD itself is no longer a TYPE? Than if you would save the CHILD again as TYPE. It would make the CHILD to a new PARENT, which is a new TYPE.

 Or did i understand it worng.

**Comment by michelguerin** [comment]
Lissi, your question make me realize that I'm not sure about the plugin boundaries and context.

Is not the use case of this plugin to create empty types/templates designs as placeholder, that then will be used outside of the scope of the plugin, and therefore all elements can be considered as a type/template inside this specific plugin?

Not-so-related question : do one need the ability to create clones or parenting relations outside of the context of the creation of the current design?

**Comment by clepski** [comment]
Take a look at the existing type structure in SCD files, parts are taken from the compas demo SCD. So the parent `<LNodeType>` uses a reference to a `<DOType>` by using a regular `<DO type="...">` with a type reference. I think we should stick to this pattern for the new types like `<BayType>` and `<IEDType>`.

> \<DataTypeTemplates\>
      \<LNodeType id="SIPROTEC5_LNType_LPHD_Application" lnClass="LPHD"\>
      \<DO name="PhyNam" type="SIPROTEC5_DOType_DPL_V07.80.17_V02.00.00"/\>
...
\<LNodeType/\>
...
\<DOType cdc="DPL" id="SIPROTEC5_DOType_DPL_V07.80.17_V02.00.00"\>
  \<DA bType="VisString255" fc="DC" name="vendor" valKind="RO"/\>
...
\</DOType\>

**Comment by LissiEitel** [comment]
@PhilipLeddin still needed? I think it was an old discussion from older concept?

**Comment by michelguerin** [comment]
Closing it as the scope changed and the spike is now not relevant.
