### ISSUE TITLE
Spike: Type-Elements – Hierarchy

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-plugins#64]
As a user, I only want the type-elements to be created in the correct hierarchy, as this is the only correct order.

ACs:
Hierarchy Restrictions:
- [ ] Type elements can only be created in the correct hierarchy:
- [ ] Substation can contain: voltage levels
- [ ] Voltage level can contain: bay
- [ ] Bay can contain: IED
- [ ] IED can contain: LD

Possible Combinations:
- [ ] Following variations are possible:
- [ ] substation+voltage levels
- [ ] substation+voltage levels+bays
- [ ] substation+voltage levels+bays+IEDs
- [ ] substation+voltage levels+bays+IEDs+LDs

Single Elements:
- [ ] substation without all other elements
- [ ] voltage levels without all other elements
- [ ] bays without all other elements
- [ ] IEDs without all other elements
- [ ] LDs without all other elements

**Comment by michelguerin** [comment]
This might be deprecated in favor of #87 an #90 
@PhilipLeddin I let you decide if we need to close this issue.
