### ISSUE TITLE
Show Bays in diagram overview

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-plugins#68]
As a user I want to see the bays in the diagram overview to get a better understanding which IEDs are part of which bay.

ACs:
- [ ] show bays in diagram overview (decision and concept from ticket 65)
- [ ] reorganize the diagram overview based on the new added bays (no concept yet)
- [ ] It is possible to see which IEDs are part of which bays
- [ ] bays are displayed as a small outline (similar to the Network Explorer) around the IEDs

Hints:
- Spike to discuss possible solutions:
https://github.com/sprinteins/oscd-plugins/issues/65

**Comment by michelguerin** [comment]
Waiting for customer feedback

**Comment by michelguerin** [comment]
Linked to #207

**Comment by michelguerin** [comment]
Conflicts between Communication Explorer changes and components inside uilib needs to be fixed.
