### ISSUE TITLE
Show Bays in sidebar

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-plugins#69]
As a user I want to see the bays in the sidebar to get a better understanding which IEDs are part of which bay.

ACs:
- [x] show the bay in the sidebar above the IED
- [x] when selecting multiple IED – the bay will be displayed always directly above each IED
- [x] It is possible to see which IEDs are part of which bays

**Comment by pwinkelholzS1** [comment]
implemented with #232

**Comment by LissiEitel** [comment]
From UX side it looks fine. But i think it also depends what solution the customer prefers for the diagram. Because if they choose the labels then i would say it makes sense to use the labels for the bays also in the sidebar. @PhilipLeddin what do you think?

**Comment by pwinkelholzS1** [comment]
maybe this can be merged for now and if we decide to use the labels the design can be adjusted?
