### ISSUE TITLE
Multi Select IEDs in sidebar

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-plugins#71]
As a user, I want to select additional IEDs in the sidebar to view the details of multiple IEDs and their connections, as the multi-selection in the diagram via Shift is not self-explanatory.

ACs:
- [ ] it is possible to select multiple IEDs via the sidebar
- [ ] it should be possible to unselect IEDs via the sidebar
- [ ] the same details are displayed as when you currently select multiple IEDs via the diagram
