### ISSUE TITLE
Display Board with Six Parts

### ISSUE THREAD

**Issue by michelguerin** [sprinteins/oscd-plugins#89]
# Story: display a board with six parts

**As** an User
**I want to** see a board with six parts (Substation, Voltage Level, Bay, IED, Logical Device, Logical Nodes)
**So that** I can organize and manage the elements efficiently.

## Acceptance Criteria:

- [ ] The board should display six columns labeled: Substation, Voltage Level, Bay, IED, Logical Device, Logical Nodes.
- [ ] Each column should have a header with the respective label.
- [ ] Each column should have a button at the end to add a new element of that type.

Original design mockups:

![image](https://github.com/user-attachments/assets/f720eaa5-42fd-4db8-a238-b10b68321c5a)
![image](https://github.com/user-attachments/assets/dff5a267-a0a6-48aa-84b6-81b1836bdc2b)

**Comment by michelguerin** [comment]
Closed and merged by #152
