### ISSUE TITLE
Add New Elements to board columns

### ISSUE THREAD

**Issue by michelguerin** [sprinteins/oscd-plugins#90]
# Story: Add new elements

**As** an User
**I want to** add new elements to each part of the board
**So that** I can expand the model as needed.

## Acceptance Criteria:

- [ ] Each column should have an "Add {Element}" button.
- [ ] Clicking the button should add a new card to the respective column.
- [ ] The new card should have default values.

## Current state
This issue is being merged into #89. Currently under development in ticket #114

**Comment by PhilipLeddin** [comment]
@illia-solovei-s1 : Feedback from Review:

Delete: Add Logical Node button in last column

**Comment by PhilipLeddin** [comment]
@illia-solovei-s1 

Bug: New LD is a IED in TypeDesigner

**Comment by michelguerin** [comment]
Closed and merged by #152
