### ISSUE TITLE
Highlight Selected Element

### ISSUE THREAD

**Issue by michelguerin** [sprinteins/oscd-plugins#91]
# Story: Highlight Selected Element

**As** a User
**I want to** highlight the selected element and its path
**So that** I can easily navigate through the elements.

## Acceptance Criteria:

- [ ] Clicking on a type should highlight it.
- [ ] Clicking on a typeRef should highlight it and the corresponding type in the next columns and so on
- [ ] Only one path should be highlighted at a time.

**Comment by michelguerin** [comment]
Dependent from #93

**Comment by michelguerin** [comment]
Conception:
1. We may use a svelte derived store to be able to manage the updates from active elements and cards to highlights

**Comment by michelguerin** [comment]
@PhilipLeddin is this feature still needed ?
The path is not the same as the beginning with fewer elements.
We might rethink the whole concept of highlighting.

**Comment by michelguerin** [comment]
Closed because not relevant with the new structure.
