### ISSUE TITLE
Drag and Drop Elements to Create Type References

### ISSUE THREAD

**Issue by michelguerin** [sprinteins/oscd-plugins#94]
Story: Drag and Drop Elements to Create Type References

**As** a User
**I want to** drag and drop elements to the column just to the left
**So that** I can create type references and establish relationships between elements.

## Acceptance Criteria:

- [x] Types should be draggable within their respective columns.
- [x] Types should be droppable only to the column immediately to the left.
- [x] A drop space should appear to give the user a clue where to leave the card
- [x] Dropping a type should create a _type reference_ card in the target column and make changes persistent.
- [x] Elements should not be draggable to the right or to non-adjacent columns.
- [x] LN should be allow in each columns

Hints:
- sync with Lissi (Multiselect)

**Comment by michelguerin** [comment]
Dependent from #93

**Comment by michelguerin** [comment]
@PhilipLeddin is this feature also used to reorder types within the same column ? 
ie. : I have three bay type :
* Bay one
* Bay two
* Bay three

And I drag and drop elements so that I have:
* Bay two
* Bay three
* Bay one

displayed on screen and persisted in the XML in that specific order.

**Comment by michelguerin** [comment]
@trusz Which library do we want to use to enable the drag n drop feature? StateFlow seems like a good choice, strong opinion against it?

**Comment by LissiEitel** [comment]
> @PhilipLeddin @LissiEitel is this feature also used to reorder types within the same column ? ie. : 
> displayed on screen and persisted in the XML in that specific order.
> 
> If so, this US could be splitted in two parts :
> 
> * first: drag and drop - rearranging elements
> * second : drag and drop - create refs

I would say frist drag and drop to the create refs. Second rearranging elements. Rearranging could be also another US.

**Comment by PhilipLeddin** [comment]
<img width="1014" alt="Image" src="https://github.com/user-attachments/assets/999ccc81-eab7-4804-914b-de4a3f4a1916" />
